# Generated by Django 5.2.6 on 2025-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestprogress',
            name='end_question',
            field=models.IntegerField(blank=True, null=True, verbose_name='Конечный вопрос диапазона'),
        ),
        migrations.AddField(
            model_name='usertestprogress',
            name='start_question',
            field=models.IntegerField(blank=True, null=True, verbose_name='Начальный вопрос диапазона'),
        ),
    ]
