# Generated by Django 5.2.6 on 2025-09-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_usertestprogress_end_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestprogress',
            name='end_question',
            field=models.IntegerField(blank=True, null=True, verbose_name='Конечный вопрос'),
        ),
        migrations.AlterField(
            model_name='usertestprogress',
            name='start_question',
            field=models.IntegerField(blank=True, null=True, verbose_name='Начальный вопрос'),
        ),
    ]
