# Generated by Django 5.2.6 on 2025-09-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_usertestprogress_end_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestprogress',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала теста'),
        ),
        migrations.AddField(
            model_name='usertestprogress',
            name='test_type',
            field=models.CharField(choices=[('normal', 'Обычный тест'), ('express', 'Экспресс-тест')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='usertestprogress',
            name='time_limit_minutes',
            field=models.IntegerField(default=0, verbose_name='Лимит времени (минуты)'),
        ),
    ]
