# Generated by Django 5.2.6 on 2025-09-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения теста'),
        ),
        migrations.AddField(
            model_name='usertestprogress',
            name='correct_answers_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество правильных ответов'),
        ),
        migrations.AddField(
            model_name='usertestprogress',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Результат в процентах'),
        ),
        migrations.AddField(
            model_name='usertestprogress',
            name='total_questions_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общее количество вопросов'),
        ),
    ]
