# Generated by Django 5.2.6 on 2025-09-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_usertestprogress_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertestprogress',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='usertestprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usertestprogress',
            name='attempt_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
