# Generated by Django 5.2.6 on 2025-09-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_usertestprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department_code',
            field=models.CharField(blank=True, help_text="Формат: Группа-Подгруппа-Подподгруппа (например: 35-1-1). Добавьте 'У' для прав просмотра", max_length=50, null=True, verbose_name='Код подразделения'),
        ),
    ]
