# Generated by Django 5.2.6 on 2025-09-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_alter_userprofile_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, help_text='Введите ваше имя', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, help_text='Введите вашу фамилию', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Введите ваше отчество', max_length=100, verbose_name='Отчество'),
        ),
    ]
