# Generated by Django 5.2.6 on 2025-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestprogress',
            name='question_order',
            field=models.JSONField(blank=True, null=True, verbose_name='Порядок вопросов в экспресс-тесте'),
        ),
    ]
