# Generated by Django 5.2.6 on 2025-09-30 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_usertestprogress_question_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.IntegerField(default=20, verbose_name='Количество вопросов')),
                ('time_limit_minutes', models.IntegerField(default=45, verbose_name='Лимит времени (минуты)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField(verbose_name='Время начала зачета')),
                ('ends_at', models.DateTimeField(verbose_name='Время окончания зачета')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('question_order', models.JSONField(verbose_name='Порядок вопросов')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'verbose_name': 'Сессия зачета',
                'verbose_name_plural': 'Сессии зачетов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.usertestprogress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tests.quizsession')),
            ],
            options={
                'verbose_name': 'Участник зачета',
                'verbose_name_plural': 'Участники зачетов',
                'unique_together': {('quiz_session', 'user')},
            },
        ),
    ]
