# Generated by Django 5.2.6 on 2025-09-30 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_quizsession_quizparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestprogress',
            name='quiz_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='tests.quizsession'),
        ),
    ]
