# Generated by Django 5.2.6 on 2025-09-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_usertestprogress_quiz_session'),
        ('tests', '0014_usertestprogress_end_time'),
    ]

    operations = [
    ]
