# Generated by Django 5.2.6 on 2025-09-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_merge_20250930_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='manually_activated',
            field=models.BooleanField(default=False, verbose_name='Активирован вручную'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
